[[VALIDATORS]]
public_key = "nHUnzYnoC5LzfxjWrm5RjyhXiWs74NF9sA6MUyiioxr6ejLzB68d"
attestation="0ADAAAA8104E7DE15D019796571E4E64736728460FB2AAA03D276340F4B3448C0DF23B42C1CA055901A3FB54941723554D317F77461CD1C6D1058CD7C9994506"

[[PRINCIPALS]]
name = "Tachyon Xrpl Validator (US-East)"
email = "tachyon-xrpl-validator@proton.me"
