[[VALIDATORS]]
public_key = "nHUnzYnoC5LzfxjWrm5RjyhXiWs74NF9sA6MUyiioxr6ejLzB68d"
attestation="5C5A7E8456EB72F75EEAA1D7C4635E119E8B2D60AD08F9478F4EB22889DADF4AB79009ED50496F9A86FAAE202966D253227BADFB2AC62250889D64FE70175504"

[[PRINCIPALS]]
name = "Bugatti Validator (US-East)"
email = "bugatti-xrp-node@proton.me"
